### ISSUE TITLE
Incidents being deleted by background process

### ISSUE THREAD

**Issue by kimx** [coderrapp/codeRR.Server#49]
My latest Incidents create date is 2017/12/07. Today, I want to view my incidents but cannot found it.I check database table Incidents that just only have before 2017/11/20 data I can find.
![error](https://user-images.githubusercontent.com/5724118/33812329-7da514d6-de57-11e7-9db0-78ab76123191.jpg)
[OneTrueError.log](https://github.com/coderrapp/codeRR.Server/files/1546299/OneTrueError.log)

**Comment by kimx** [comment]
I tracking the source code then find the bug code.The incidents will be deleted after two days later.
![error-delete](https://user-images.githubusercontent.com/5724118/33814405-f2f1982e-de64-11e7-8603-b0a3fa0c8198.jpg)

**Comment by jgauffin** [comment]
That is by design. Under Admin/Reports there is a setting called "Retention days" that specify the number of days that error reports can exist in the system.

The flow works like this:

A background job looks for ErrorReports that are older then the RetentionDays setting (default is 90 days). All reports that are older than that is deleted (`DeleteOldReports.cs`)

Another background job looks for incidents that do not have any error reports (i.e. all reports have been deleted since they were older than 90 days). Then the incident itself is cleaned up (`DeleteEmptyIncidents.cs`).

**Comment by jgauffin** [comment]
However, I think that I've missed parenthesis in the code that you showed.

**Comment by kimx** [comment]
But, I think that is your SQL "or" lack of "(" and ")". You can try your new incidents once after two days it will be deleted whenever its any status.

**Comment by jgauffin** [comment]
yep. correct.

**Comment by kimx** [comment]
You mean that is not bug?

**Comment by jgauffin** [comment]
It's a bug. I've corrected it and are running through a test suite.

**Comment by kimx** [comment]
ok, thanks.
